name: Build and Deploy to Cloud Run

env:
  PROJECT_ID: cosmic-strategy-424512-v2
  GCP_HOST: eu.gcr.io
  IMAGE_NAME: driftdataan-prod
  SERVICE_NAME: driftdataan-prod
  REGION: europe-north1
  DOCKERFILE: Dockerfile

on:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: docker/login-action@v3
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_SERVICE_ACCOUNT }}
      - name: Docker build & push
        run: |
          docker build -t $IMAGE_NAME -f $DOCKERFILE .
          docker tag $IMAGE_NAME $GCP_HOST/$PROJECT_ID/$IMAGE_NAME:latest
          docker push $GCP_HOST/$PROJECT_ID/$IMAGE_NAME:latest

  google-cloud-run:
    needs:
      - build-and-push-to-gcr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_SERVICE_ACCOUNT }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Use gcloud CLI
        run: gcloud info
      - name: Google Cloud run deploy & update-traffic
        run: |
          export RAW_VERSION=$(cat package.json | jq -r .version)
          export VERSION=${RAW_VERSION//./-}
          export RANDOM_STRING=$(openssl rand -hex 3)
          gcloud run deploy $SERVICE_NAME \
            --image $GCP_HOST/$PROJECT_ID/$IMAGE_NAME:latest \
            --platform managed \
            --region $REGION \
            --revision-suffix=$RANDOM_STRING-v$VERSION \
            --no-traffic
